### ISSUE TITLE
Open/ask about the Issue ?? here, so that anyone on github can help you

### ISSUE THREAD

**Issue by ng-model** [klee5760/Assignment-3-Word-Guess#1]

**Comment by klee5760** [comment]
I will try myself on this assignment later, but let's focus on #4 first.

**Comment by klee5760** [comment]
I will try myself on this assignment later, but let's focus on #4 first.

**Comment by ng-model** [comment]
Dear @klee5760 
you need to open the issue, and explain the problem, what did you try, and what failed, what are you trying to achieve and what's not working for anyone to understand and help you(saves time on both ends)
